name: 'ğŸ”ï¸ Lint Code'
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Lint and format checks
    steps:
      - name: 'ğŸšš Checkout'
        uses: actions/checkout@v6
      - name: 'ğŸ”§ Setup Bun'
        uses: oven-sh/setup-bun@v2
      - name: 'ğŸ“¦ï¸ Install dependencies'
        run: bun install
      - name: 'ğŸ”ï¸ Run lint and format checks'
        run: bun lint
