name: 'ğŸ§ª Run Tests'
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Testing on Node ${{ matrix.node }}
    steps:
      - name: 'ğŸšš Checkout'
        uses: actions/checkout@v6
      - name: 'ğŸ”§ Setup Bun'
        uses: oven-sh/setup-bun@v2
      - name: 'ğŸ“¦ï¸ Install dependencies'
        run: bun install
      - name: 'ğŸ§ª Run Unit tests'
        run: bun test
      - name: 'âš—ï¸ Run CI test'
        uses: ./
        with:
          path: tests/ci/default/bun.lock
          token: ${{ secrets.GITHUB_TOKEN }}
